# Generated by Django 5.2.6 on 2025-11-21 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('minimum_verification_score', models.IntegerField(default=0)),
                ('required_verification_methods', models.JSONField(default=list)),
                ('access_level', models.CharField(choices=[('basic', 'Basic'), ('verified', 'Verified'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_description', models.TextField(blank=True)),
                ('blocked_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('verification_level_required', models.CharField(choices=[('unverified', 'Unverified (0-30%)'), ('basic', 'Basic (31-69%)'), ('verified', 'Verified (70%+)')], max_length=20)),
                ('feature_category', models.CharField(choices=[('booking', 'Booking & Housing'), ('listing', 'Listing Access'), ('community', 'Community Features'), ('payment', 'Payment & Discounts'), ('priority', 'Priority Access'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('university', models.CharField(max_length=200)),
                ('student_id_number', models.CharField(blank=True, max_length=50)),
                ('expected_graduation_year', models.IntegerField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('verification_methods', models.JSONField(default=list)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_additional_info', 'Requires Additional Information')], default='pending', max_length=30)),
                ('student_id_document', models.FileField(blank=True, null=True, upload_to='student_verifications/documents/')),
                ('additional_documents', models.JSONField(default=list)),
                ('ocr_extracted_text', models.TextField(blank=True)),
                ('document_analysis_results', models.JSONField(default=dict)),
                ('university_logo_detected', models.BooleanField(default=False)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('document_is_valid', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verification_code', models.CharField(blank=True, max_length=6)),
                ('phone_verification_expires', models.DateTimeField(blank=True, null=True)),
                ('university_email', models.EmailField(blank=True, max_length=254)),
                ('university_email_verified', models.BooleanField(default=False)),
                ('university_domain_valid', models.BooleanField(default=False)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('facebook_profile', models.URLField(blank=True)),
                ('social_media_verified', models.BooleanField(default=False)),
                ('peer_verifications', models.JSONField(default=list)),
                ('peer_verification_count', models.IntegerField(default=0)),
                ('peer_verification_required', models.IntegerField(default=2)),
                ('registration_location', models.JSONField(default=dict)),
                ('campus_proximity_verified', models.BooleanField(default=False)),
                ('location_verification_optional', models.BooleanField(default=True)),
                ('agent_review_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_additional_info', 'Requires Additional Information')], default='pending', max_length=30)),
                ('agent_notes', models.TextField(blank=True)),
                ('agent_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_score', models.IntegerField(default=0)),
                ('minimum_score_required', models.IntegerField(default=70)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_personally', models.BooleanField(default=False)),
                ('same_university', models.BooleanField(default=False)),
                ('confidence_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewed_by_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verifying_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_verifications_given', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_verifications_records', to='verification.studentverification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('student_id', 'Student ID Card'), ('enrollment_letter', 'Enrollment Letter'), ('transcript', 'Academic Transcript'), ('tuition_receipt', 'Tuition Receipt'), ('class_schedule', 'Class Schedule'), ('library_card', 'Library Card'), ('other', 'Other')], max_length=30)),
                ('document_file', models.FileField(upload_to='student_verifications/additional_docs/')),
                ('ocr_text', models.TextField(blank=True)),
                ('analysis_results', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.studentverification')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationGateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=100)),
                ('access_granted', models.BooleanField(default=False)),
                ('verification_score_at_time', models.IntegerField(default=0)),
                ('required_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('blocking_reason', models.TextField(blank=True)),
                ('verification_methods_completed', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_gate_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('student_id_upload', 'Student ID Document Upload'), ('university_email', 'University Email Verification'), ('phone_verification', 'Phone Number Verification'), ('social_media', 'Social Media Verification'), ('peer_verification', 'Peer Verification'), ('geolocation', 'Geolocation Verification'), ('agent_manual_review', 'Agent Manual Review')], max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('step_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='verification.studentverification')),
            ],
            options={
                'ordering': ['verification', 'step_type'],
            },
        ),
        migrations.AddIndex(
            model_name='studentverification',
            index=models.Index(fields=['user', 'overall_status'], name='verificatio_user_id_97b804_idx'),
        ),
        migrations.AddIndex(
            model_name='studentverification',
            index=models.Index(fields=['assigned_agent', 'agent_review_status'], name='verificatio_assigne_2c616f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentverification',
            index=models.Index(fields=['verification_score'], name='verificatio_verific_859d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerverification',
            unique_together={('verification', 'verifying_student')},
        ),
        migrations.AddIndex(
            model_name='verificationgatelog',
            index=models.Index(fields=['user', 'feature', '-timestamp'], name='verificatio_user_id_c2f605_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationgatelog',
            index=models.Index(fields=['access_granted', '-timestamp'], name='verificatio_access__707ce2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationstep',
            unique_together={('verification', 'step_type')},
        ),
    ]
