# Generated by Django 5.2.6 on 2025-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_featureaccessconfig_verificationbenefit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureaccessconfig',
            options={'ordering': ['feature_name'], 'verbose_name': 'Feature Access Configuration', 'verbose_name_plural': 'Feature Access Configurations'},
        ),
        migrations.AlterModelOptions(
            name='verificationbenefit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Verification Benefit', 'verbose_name_plural': 'Verification Benefits'},
        ),
        migrations.AlterField(
            model_name='featureaccessconfig',
            name='blocked_message',
            field=models.TextField(blank=True, help_text='Message shown to users when access is denied'),
        ),
        migrations.AlterField(
            model_name='featureaccessconfig',
            name='required_verification_methods',
            field=models.JSONField(default=list, help_text='List of verification methods that must be completed'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verification_type',
            field=models.CharField(choices=[('student_id', 'Student ID'), ('national_id', 'National ID'), ('property_proof', 'Proof of Property'), ('enrollment', 'Enrollment Letter'), ('profile_photo', 'Profile Photo'), ('address', 'Address Proof')], max_length=30),
        ),
    ]
