# Generated by Django 5.2.6 on 2025-11-22 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_featureaccessconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationExpirationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('warning_30_days', '30 Days Warning'), ('warning_7_days', '7 Days Warning'), ('expired', 'Expired Notification'), ('grace_period', 'Grace Period Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('days_until_expiration', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
                ('in_app_notification_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_type', models.CharField(choices=[('university_email', 'University Email'), ('student_id', 'Student ID'), ('enrollment', 'Enrollment Verification'), ('full', 'Full Verification Renewal')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('documents_submitted', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_renewals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_email_expires_at', models.DateTimeField(blank=True, null=True)),
                ('student_id_expires_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('last_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('expiration_warning_sent', models.BooleanField(default=False)),
                ('expiration_notification_sent', models.BooleanField(default=False)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('in_grace_period', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_expiration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'status'], name='verificatio_expires_6bafdd_idx'), models.Index(fields=['status'], name='verificatio_status_9c9f9f_idx')],
            },
        ),
    ]
