# Generated by Django 5.2.6 on 2025-11-21 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage', max_digits=5)),
                ('max_applications_per_student', models.IntegerField(default=5, help_text='Maximum applications a student can submit')),
                ('maintenance_response_time', models.IntegerField(default=24, help_text='Expected maintenance response time in hours')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('auto_approval', models.BooleanField(default=False, help_text='Auto-approve applications for verified users')),
                ('verification_required', models.BooleanField(default=True, help_text='Require verification for property listings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_update', 'User Update'), ('user_role_change', 'User Role Change'), ('user_status_change', 'User Status Change'), ('property_update', 'Property Update'), ('property_verification', 'Property Verification'), ('application_action', 'Application Action'), ('payment_action', 'Payment Action'), ('settings_update', 'Settings Update'), ('ticket_action', 'Ticket Action')], max_length=50)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='admin_api_a_admin_i_bfa1cc_idx'), models.Index(fields=['action', 'created_at'], name='admin_api_a_action_0c6273_idx')],
            },
        ),
    ]
