# Generated by Django 5.2.6 on 2025-11-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_booking_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
