# Generated by Django 5.2.6 on 2025-11-21 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lease_document',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='images',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_term',
            field=models.CharField(choices=[('month-to-month', 'Month to Month'), ('6-months', '6 Months'), ('12-months', '12 Months'), ('24-months', '24 Months')], default='12-months', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('duplex', 'Duplex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.CharField(choices=[('lease', 'Lease Agreement'), ('inspection', 'Inspection Report'), ('permit', 'Permit'), ('warranty', 'Warranty'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
