# Generated by Django 5.2.6 on 2025-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
