# Generated by Django 5.2.6 on 2025-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_permissions_cache',
            field=models.JSONField(default=dict, help_text='Cached access permissions for performance optimization'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_verification_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_level',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('basic', 'Basic'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=20),
        ),
    ]
